<template>
  <!-- 
    Transition is special vue built-in component that allows 
    us to animate elements when they are added or removed from the DOM,
    hidden and shown, or when their state changes.

    The name attribute is used to define the name of the transition.
    This name is used to generate the CSS classes that will be applied
    to the element during the transition.

    Custom transition classes can be bind to the element using the
    v-bind:class directive. The classes are generated based on the
    name attribute that we defined in the template.

    We can also bind to the events that are emitted by the Transition
    component. The events are emitted at different stages of the transition.
  -->
  <Transition name="fade" enter-active-class="fade-enter-active" @before-enter="onBeforeEnter">
    <slot></slot>
  </Transition>
</template>

<script setup lang="ts">
const onBeforeEnter = () => {
  console.log('Before enter animation...')
}
</script>
<style>
/* 
  The CSS classes that are generated by the Transition component
  are based on the name attribute that we defined in the template.
  In this case, the name is "fade", so the classes will be "fade-enter",
  "fade-enter-active", "fade-leave", and "fade-leave-active".

  Each class is applied to the element at different stages of the transition.
    - fade-enter: applied when the element is added to the DOM
    - fade-enter-active: applied when the element is being added to the DOM
    - fade-leave: applied when the element is removed from the DOM
    - fade-leave-active: applied when the element is being removed from the DOM
*/
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.5s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
